### PR TITLE
@ #94 | inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()

### PR DESCRIPTION
**Pull request by hoatle**
connect #94

### CODE REVIEW

**Comment by halfdan** [comment]
Can we get a release with this change? I see a 0.15 being planned but it would be nice to get a 0.14.2 just to get rid of the deprecation warnings in our codebase.

**Comment by hoatle** [comment]
sure, let me release v0.14.2 to have this change.

**Comment by halfdan** [comment]
@hoatle Any update on 0.14.2?

**Comment by hoatle** [comment]
@halfdan it was planned, could be availabe soon (in 2 weeks), it needs more work for the CI and docs fixes

**Comment by hoatle** [comment]
@halfdan all the related tasks were moved to our current sprint, hopefully, v0.14.2 will be available today, you can track all related issues here https://github.com/teracyhq/flask-classful/milestone/12

**Comment by hoatle** [comment]
@halfdan flask-classful v0.14.2 is available https://github.com/teracyhq/flask-classful/releases/tag/v0.14.2 https://pypi.org/project/Flask-Classful/0.14.2/

**Comment by halfdan** [comment]
Thank you so much @hoatle!

**Pull request merged**
