### PR TITLE
@ #50 | base_args should not be overriden when route_base is set

### LINKED ISSUE #50: base_args is overriden when route_base is set
Hi, I was trying to combine flask-classful with webargs to make my API, this is an example code of how I did it, based on the quotes example in the docs:

```python
from flask import Flask
from flask_classful import FlaskView
from webargs.flaskparser import use_args
from webargs import fields

# we'll make a list to hold some quotes for our app
quotes = [
    "A noble spirit embiggens the smallest man! ~ Jebediah Springfield",
    "If there is a way to do it better... find it. ~ Thomas Edison",
    "No one knows what he can do till he tries. ~ Publilius Syrus"
]

app = Flask(__name__)
app.config['DEBUG'] = True

put_args = {
    "text": fields.Str(required=True)
}

class QuotesView(FlaskView):
    base_args = ['args']
    def index(self):
        return "<br>".join(quotes)

    def get(self, id):
        id = int(id)
        if id < len(quotes) - 1:
            return quotes[id]
        else:
            return "Not Found", 404

    @use_args(put_args)
    def put(self, args, id):
        id = int(id)
        if id >= len(quotes) - 1:
            return "Not Found", 404
        quotes[id] = args['text']
        return quotes[id]

QuotesView.register(app)

if __name__ == '__main__':
    app.run()
```
The interesting part of this is the use of the @use_args decorator, that adds an argument `args` to the put function when called. To avoid having a `/quotes/<args>/<id>/` URL (it should be `/quotes/<id>/`) i set the base_args class attribute to `['args']` so that parameter is ignored from the URL. (BTW this isn't documented, i had to manually look the code to understand it). Until now everything works as expected.

The problem comes when I want to set the route_base atribute so it isn't automatically calculated from the class name:

```python
# ...

class UglyNameClass(FlaskView):
    base_args = ['args']
    route_base = 'quotes'
    # ...
    @use_args(put_args)
    def put(self, args, id):
        id = int(id)
        if id >= len(quotes) - 1:
            return "Not Found", 404
        quotes[id] = args['text']
        return quotes[id]

UglyNameClass.register(app)
```

This should be routed to `/quotes/<id>/` as the previous example, but it gets routed as `/quotes/<args>/<id>/`, ignoring the base_args parameter I set.

Digging into the flask-restful code I saw that in get_route_base() the base_args is overriden when route_base exist:
```
    @classmethod
    def get_route_base(cls):
        """Returns the route base to use for the current class."""

        if cls.route_base is not None:
            route_base = cls.route_base
            base_rule = parse_rule(route_base)
            cls.base_args = [r[2] for r in base_rule]  # THE PROBLEM IS HERE
        else:
            route_base = cls.default_route_base()

        return route_base.strip("/")
```

I'm not sure why it overrides the value, but I think that it would be good to append to base_args instead of overriding it to support this use case.

It would be great to fix it to I could use views using webargs with a custom route_base

### PR DESCRIPTION
**Pull request by hoatle**
connect #50

### CODE REVIEW

**Comment by sh4r3m4n** [comment]
Hi again! I realized there is a bug in this fix. You are redefining the class attribute `base_args` to be the concatenation of its previous value and another non-empty list. Since this is done on each request, the list will grow indefinitely. For example, using the code in #50, `UglyNameClass.base_args` will eventualy have the value:
```
['args', 'quotes', 'quotes', 'quotes', 'quotes', ..., 'quotes']
```
To fix it you should check that the values weren't added before. I think the order is not important in `base_args` so something like this will probably work:
```python
cls.base_args = list(set(cls.base_args) + set(r[2] for r in base_rule))
```

**Comment by sh4r3m4n** [comment]
Correction, the code that will probably work should be like this:
```python
cls.base_args = list(set(cls.base_args).union(r[2] for r in base_rule))
```

I didn't know that set concatenation was invalid in python :P

**Comment by hoatle** [comment]
@sh4r3m4n thank you for your valuable feedback, let me check and update the code accordingly.

**Comment by hoatle** [comment]
@sh4r3m4n it should be fixed now 👯‍♂️ https://github.com/teracyhq/flask-classful/commit/baf37cd8a1f9f1124d32c1376135968172aa6b7b

**Comment by sh4r3m4n** [comment]
@hoatle Great!!

**Pull request merged**
