### PR TITLE
Small changes to enable using custom decorators in FlaskView

### PR DESCRIPTION
**Pull request by mattbillenstein**
These changes allow me to remove most of the boilerplate use of @route as well as use custom decorators to coerce arguments to view functions.

### CODE REVIEW

**Comment by hoatle** [comment]
@mattbillenstein thank you for your PR, could you add tests for the changes?

**Comment by hoatle** [comment]
@mattbillenstein could you give some code examples to show why we need these changes?

**Comment by mattbillenstein** [comment]
Yes, i'm out of the country at the moment, but perhaps this week.

M

--
Matt Billenstein
matt@vazor.com

**Comment by mattbillenstein** [comment]
Hey guys, sorry, I haven't had time for this until today.

So, a short example:

`
class HelloView(FlaskView):
    default_methods = ('GET', 'POST')
    inspect_args = False

    @annotate(name=unicode)
    def hello(self, name=u'mattb'):
        print current_user.get_id()
        return render('hello/hello.mako', locals())
`

Here, I'm using a custom decorator (@annotate) to essentially "annotate" or coerce params to a given type.  The keyword arguments act as a default if the param isn't given in the request -- I need to skip the default argument inspection in flask-classful to allow this to work, so 'inspect_args = False' is just allowing me to further customize how methods in the view handle get/post data.

The default_methods attribute allows me to omit the route decorator to specify allowing both GET and POST methods.  Of course, we can add @route to limit a method to GET or POST as needed still.  Note, this isn't required and just allows overriding the implicit default GET-only behavior in flask.

So really, this pull request is just adding a couple hooks for further customization of what the default view behaviors are.  This may be useful to someone trying to customize how they call methods in views or roll their own decorators for handling custom request bodies/parameters.

Let me know if this makes sense for inclusion -- or if I should just maintain this in my own fork.  I haven't looked at writing tests, but I should be able to find some time for that if needed.

**Comment by hoatle** [comment]
@mattbillenstein thank you for your information, it's very helpful, I'm going to look into this.

**Comment by hoatle** [comment]
Hello @mattbillenstein, after looking more deeply into the issue, I'm not sure if your changes fit the way Flask-Classful works (I know you want to customize it). I need to look into it more closely to see if we really need it for the roadmap ahead: trying to make it simpler, lightweight with customization and plays well along with https://webargs.readthedocs.io/en/latest/ to develop REST APIs.

So at the moment, let's hold the changes off until we have better-detailed plan and roadmap. You should keep this in your fork and we'll look into this later.

Thank you for your suggested changes.

**Comment by mattbillenstein** [comment]
Right on -- I'd think about the calling convention here vs webargs tho -- it does seem like a nicely documented library, but the syntax is pretty ugly IMHO (intparam=fields.Int() vs intparam=int).

Using an api where the type is just a callable that either does the correct thing or raises, and you inject defaults using built-in python functionality is 80% of what webargs is trying to do and I think and much easier to read.

**Comment by blurrcat** [comment]
@mattbillenstein for pretty syntax, type hints might be the way to go: #34. 
Currently it only supports a few simple types, 'cause these are what flask supports out of the box. It's easy to adapt that to what you want.
To use type hints with older versions of Python, try `pip install` these:
* 3.2 - 3.4: [typing](https://pypi.python.org/pypi/typing/3.5.2)
* 2: [typeshed](https://github.com/python/typeshed)

Despite its "ugliness", I think for anything a little more complex, you'll need webargs or a serialization layer like marshmallow.

**Comment by hoatle** [comment]
@mattbillenstein could you add tests to cover for the changes? and rebase, too.

After that, I guess we can merge the changes.

**Comment by mattbillenstein** [comment]
@hoatle alright, I'll take a crack at that.

**Comment by mattbillenstein** [comment]
Rebased and added tests for default_methods and inspect_args -- let me know if those look alright.

Seems the other change related to not routing methods from base classes was already implemented.

**Comment by hoatle** [comment]
@mattbillenstein there are some failed tests, please make sure all tests should pass https://travis-ci.org/teracyhq/flask-classful/builds/240321388

**Pull request merged**
