### PR TITLE
removed unnecessary -1 on len for get example

### PR DESCRIPTION
**Pull request by j2dunham**

### CODE REVIEW

**Comment by hoatle** [comment]
-1 is needed, otherwise, http://localhost:5000/quotes/3/ will throw error

**Comment by j2dunham** [comment]
http://localhost:5000/quotes/3/ should return a 404 because 0,1 and 2 are the only valid indexes for quotes

**Comment by j2dunham** [comment]
Without this change http://localhost:5000/quotes/2/ will incorrectly return a 404.

**Comment by hoatle** [comment]
@j2dunham my bad, could you fix this on the docs/index.rst too?

**Pull request merged**
