### PR TITLE
Added ViewRegistration Class

### PR DESCRIPTION
**Pull request by janscas**
Utility to easily register complete view modules with custom params

### CODE REVIEW

**Comment by janscas** [comment]
Hope you find some interest in this utility.
I was Registering a lot of Views with the same params later on so that's why I did this utility

**Comment by hoatle** [comment]
@janscas thank you for your PR, the utility looks good to me. Could you rebase, add unit tests and docs so that we can add it to the current codebase?

**Comment by janscas** [comment]
@hoatle I don't have the time for the moment. I'll maybe in the future. Thanks.

**Comment by hoatle** [comment]
let's close this PR for now until we get a better one.

**Pull request closed without merging**
