### PR TITLE
Support Flask-Injector by allowing view arguments to be altered

### LINKED ISSUE #48: injection of dependencies into class
Hello,

What is the way to inject dependencies into the views? 
Is there a way I can have and pass stuff into `__init__`, say a database handle or any other kind of service?

Thanks

### PR DESCRIPTION
**Pull request by davidparsson**
Fixes #48 by adding support for the excellent [Flask-Injector](https://github.com/alecthomas/flask_injector).

### CODE REVIEW

**Comment by davidparsson** [comment]
Sure, I'll try to get it done, but it'll probably take a while.

Do you think the tests should use the real Injector library or a fake/stub?

**Comment by hoatle** [comment]
@davidparsson let's keep the test lightweight, using fake/stub for unit tests is good to me.

**Comment by davidparsson** [comment]
Writing a descent set of tests for this turned out to be more difficult than I thought, and since I'm not currently in need of this I'm not very likely to get this done anytime soon. Some day I might though, but feel free to close this if you want to keep it tidy.

**Comment by hoatle** [comment]
with no further update for tests, I'll close this PR without merging.

**Comment by davidparsson** [comment]
That's reasonable. I actually tried writing a bunch of tests this week but
ran into a few problems. If I ever get it done properly I'll let you know.

**Pull request closed without merging**
