### PR TITLE
Track registered endpoints

### PR DESCRIPTION
**Pull request by revmischa**
Keep track of what endpoints are registered, along with rules and context.
This enables auto-generation of swagger documentation
Flask-Classful support is here: https://github.com/jmcarp/flask-apispec/pull/69

### CODE REVIEW

**Comment by hoatle** [comment]
@revmischa thank you for your PR, could you sign the CLA and fix the CI build?

**Comment by hoatle** [comment]
@hjc let's review on this, what do you think?

**Comment by revmischa** [comment]
I think this is a terrible hack but it's the best way I could figure out how to make flask-classful work with flask-apispec.

**Comment by revmischa** [comment]
i cleaned up the auto-registration quite a bit. it doesn't need to store a special list property globally on the app object anymore. now it sets an attr on the view func.

**Comment by revmischa** [comment]
Probably not. I don't even remember what these changes were at this point. Feel free to add them if you want.

**Comment by hoatle** [comment]
with no further update for tests, I'll close this PR without merging.

**Pull request closed without merging**
